on:
  push:
    branches:
      - master
      - Set-up-GHA-CI/CD
      
  pull_request:

jobs:
  validate:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # os: [windows-latest]
        # os: [windows-latest, ubuntu-18.04]
        os: [windows-latest, ubuntu-latest, macos-latest]
        # os: [ubuntu-18.04]
    steps:
    - uses: actions/checkout@v1      
    - name: Run Continuous Integration
      shell: pwsh
      run : |
        # ./ContinuousIntegration/ContinuousIntegration.ps1
        "Hello World"