on:
  push:
    branches:
      - master
      - Set-up-GHA-CI/CD
      
  pull_request:

jobs:
  validate:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # os: [windows-latest]
        # os: [windows-latest, ubuntu-latest]
        # os: [windows-latest, ubuntu-latest, macos-latest]
        os: [ubuntu-latest]
    steps:
    - uses: actions/checkout@v1      
    - name: Run Continuous Integration
      shell: pwsh
      run : |
        # ./ContinuousIntegration/ContinuousIntegration.ps1
        apt-get -y update && apt-get install -y --no-install-recommends libgdiplus libc6-dev
        cd ./__tests__
        Invoke-Pester -Output Detailed