on:
  push:
    branches:
      - master
      - Set-up-GHA-CI/CD
      
  pull_request:

jobs:
  validate:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]
        # os: [windows-latest, ubuntu-latest, macos-latest]
    steps:
    - uses: actions/checkout@v1      
    - name: Run Continuous Integration
      shell: pwsh
      run : |
        # if($PSVersionTable.Platform -eq 'Win32NT') {
        #   'Install ACE for Invoke-ExcelQuery testing'
        #   Start-Process ./ace/ace.exe -Wait -ArgumentList "/quiet /passive /norestart"
        # } elseif ($PSVersionTable.Platform -eq 'Unix') {
        #   mkdir ./ace
        #   curl -o ./ace/ace.exe https://download.microsoft.com/download/3/5/C/35C84C36-661A-44E6-9324-8786B8DBE231/accessdatabaseengine_X64.exe
        # }

        mkdir ./ace
        Invoke-Restmethod https://download.microsoft.com/download/3/5/C/35C84C36-661A-44E6-9324-8786B8DBE231/accessdatabaseengine_X64.exe -OutFile ./ace/ace.exe
        Start-Process ./ace/ace.exe -Wait -ArgumentList "/quiet /passive /norestart"
        
        # cd ./__tests__
        # Invoke-Pester -Output Detailed


# jobs:
#   validate:    
#     strategy:
#       matrix:
#         # os: [windows-latest, ubuntu-latest, macos-latest]
#         os: [windows-latest, ubuntu-latest]
#     steps:
#     - uses: actions/checkout@v1
#     - name: Run Tests 
#       shell: pwsh
#       run : |
#         # ./ContinuousIntegration/ContinuousIntegration.ps1
#         # sudo apt-get -y update && apt-get install -y --no-install-recommends libgdiplus libc6-dev
#         # cd ./__tests__
#         # Invoke-Pester -Output Detailed
#         if($PSVersionTable.Platform -eq 'Win32NT') {
#           "start process"
#         } elseif ($PSVersionTable.Platform -eq 'Unix') {
#           "curl"
#         }

#     # runs-on: windows-latest
#     # steps:
#     # - uses: actions/checkout@v1
#     # - name: Run Tests on Windows
#     #   shell: pwsh
#     #   run : |
#     #     cd ./__tests__
#     #     Invoke-Pester -Output Detailed        